### ISSUE TITLE
デプロイ

### ISSUE THREAD

**Issue by utouto97** [utouto97/kondate#3]
Github Pages にデプロイする

**Comment by utouto97** [comment]
Github Pagesにデプロイ  
Github Actionsで自動化

```yaml
name: Build and Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install and Build 🔧
        run: |
          yarn
          yarn generate

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages 
          FOLDER: dist 
```

参考  
https://qiita.com/Ancient_Scapes/items/fe18bae043e4d35f1e39
